print ("Khansa Khalida Kennedy")
print ("I0322067")
print ("Saya tinggal di Sleman, Provinsi Yogyakarta")
print ("Tempat tinggal saya salah satu provinsi yang dikenal sebagai Kota wisata, tetapi UMR atau upah minimum yang dihasilkan kota yogyakarta paling rendah dari seluruh provinsi di Jawa. Yogyakarta juga terkenal sebagai kota pelajar karena banyak sekali sekolah sampai universitas yang ada di sini")
print ("setelah saya lulus dari Teknik Industri UNS, saya berharap bisa menjadi orang yang bermanfaat bagi sekitar saya dan bisa mencapai apa yang saya cita-citakan")
